-- ============================================================
--  Hipermascota Rafaela — Esquema de base de datos (Supabase)
--  Ejecutá este script completo en el SQL Editor de Supabase.
--  Es seguro correrlo más de una vez.
-- ============================================================

-- 1. CATEGORÍAS -------------------------------------------------
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  created_at timestamptz default now()
);

-- 2. PRODUCTOS --------------------------------------------------
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10,2) not null check (price >= 0),
  sale_price numeric(10,2) check (sale_price is null or sale_price >= 0),
  category_id bigint references categories(id) on delete set null,
  image_url text,
  images text[] not null default '{}',
  pet_type text not null default 'ambos' check (pet_type in ('perro','gato','ambos')),
  stock int not null default 0 check (stock >= 0),
  is_featured boolean default false,
  created_at timestamptz default now()
);

-- Por si la tabla products ya existía sin estas columnas:
alter table products add column if not exists sale_price numeric(10,2);
alter table products add column if not exists images text[] not null default '{}';
alter table products add column if not exists pet_type text not null default 'ambos';

-- 3. CLIENTES ---------------------------------------------------
create table if not exists customers (
  id bigint generated by default as identity primary key,
  dni text not null unique,
  first_name text not null,
  last_name text not null,
  phone text not null,
  address text,
  created_at timestamptz default now()
);

-- 4. CUPONES ---------------------------------------------------
create table if not exists coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_percent int not null check (discount_percent > 0 and discount_percent <= 100),
  max_uses int,
  uses_count int default 0,
  valid_from timestamptz default now(),
  valid_until timestamptz,
  active boolean default true,
  created_at timestamptz default now()
);

-- 5. PEDIDOS ----------------------------------------------------
create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_name text,
  customer_dni text,
  customer_phone text,
  customer_address text,
  items jsonb not null,
  total_amount numeric(10,2) not null,
  coupon_code text,
  coupon_discount numeric(10,2) default 0,
  status text default 'Pendiente' check (status in ('Pendiente','Entregado','Cancelado')),
  created_at timestamptz default now()
);

-- Por si orders existía sin cupones:
alter table orders add column if not exists coupon_code text;
alter table orders add column if not exists coupon_discount numeric(10,2) default 0;

-- Por si la tabla orders ya existía sin estas columnas:
alter table orders add column if not exists customer_name text;
alter table orders add column if not exists customer_dni text;
alter table orders add column if not exists customer_address text;

-- ============================================================
--  SEGURIDAD (Row Level Security)
-- ============================================================
alter table categories enable row level security;
alter table products   enable row level security;
alter table customers  enable row level security;
alter table orders     enable row level security;

-- Lectura pública del catálogo
drop policy if exists "lectura publica categorias" on categories;
create policy "lectura publica categorias" on categories for select using (true);

drop policy if exists "lectura publica productos" on products;
create policy "lectura publica productos" on products for select using (true);

-- La web puede registrar clientes y pedidos (solo insertar)
drop policy if exists "alta clientes desde la web" on customers;
create policy "alta clientes desde la web" on customers for insert with check (true);

drop policy if exists "alta pedidos desde la web" on orders;
create policy "alta pedidos desde la web" on orders for insert with check (true);

-- El administrador (logueado) gestiona todo
drop policy if exists "admin categorias" on categories;
create policy "admin categorias" on categories for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "admin productos" on products;
create policy "admin productos" on products for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "admin clientes" on customers;
create policy "admin clientes" on customers for select using (auth.role() = 'authenticated');

drop policy if exists "admin pedidos" on orders;
create policy "admin pedidos" on orders for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Cupones (RLS)
alter table coupons enable row level security;

drop policy if exists "lectura cupones activos" on coupons;
create policy "lectura cupones activos" on coupons for select using (active = true and valid_from <= now() and (valid_until is null or valid_until > now()));

drop policy if exists "admin cupones" on coupons;
create policy "admin cupones" on coupons for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- 6. PROMOTIONS (OFERTAS) -------------------------------------------
create table if not exists promotions (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  discount_percent int check (discount_percent is null or (discount_percent > 0 and discount_percent <= 100)),
  discount_fixed numeric(10,2) check (discount_fixed is null or discount_fixed > 0),
  discount_type text not null check (discount_type in ('percent', 'fixed')),
  image_url text,
  badge_label text default 'Promoción',
  display_priority int default 0,
  is_active boolean default true,
  valid_from timestamptz default now(),
  valid_until timestamptz,
  created_at timestamptz default now()
);

-- 7. PROMOTION_PRODUCTS (vinculación ofertas-productos) ---------------
create table if not exists promotion_products (
  id bigint generated by default as identity primary key,
  promotion_id bigint not null references promotions(id) on delete cascade,
  product_id bigint not null references products(id) on delete cascade,
  created_at timestamptz default now(),
  unique(promotion_id, product_id)
);

-- 8. PROMOTION_CATEGORIES (vinculación ofertas-categorías) --------
create table if not exists promotion_categories (
  id bigint generated by default as identity primary key,
  promotion_id bigint not null references promotions(id) on delete cascade,
  category_id bigint not null references categories(id) on delete cascade,
  created_at timestamptz default now(),
  unique(promotion_id, category_id)
);

-- Promotions (RLS)
alter table promotions enable row level security;
alter table promotion_products enable row level security;
alter table promotion_categories enable row level security;

drop policy if exists "lectura promociones activas" on promotions;
create policy "lectura promociones activas" on promotions for select using (is_active = true and valid_from <= now() and (valid_until is null or valid_until > now()));

drop policy if exists "admin promociones" on promotions;
create policy "admin promociones" on promotions for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "lectura productos promocionados" on promotion_products;
create policy "lectura productos promocionados" on promotion_products for select using (true);

drop policy if exists "admin promociones productos" on promotion_products;
create policy "admin promociones productos" on promotion_products for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "lectura categorias promocionadas" on promotion_categories;
create policy "lectura categorias promocionadas" on promotion_categories for select using (true);

drop policy if exists "admin promociones categorias" on promotion_categories;
create policy "admin promociones categorias" on promotion_categories for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- ============================================================
--  STORAGE (bucket "products" para las fotos)
--  Antes creá el bucket "products" como público desde Storage.
-- ============================================================
drop policy if exists "fotos publicas" on storage.objects;
create policy "fotos publicas" on storage.objects for select using (bucket_id = 'products');

drop policy if exists "admin sube fotos" on storage.objects;
create policy "admin sube fotos" on storage.objects for insert with check (bucket_id = 'products' and auth.role() = 'authenticated');

drop policy if exists "admin edita fotos" on storage.objects;
create policy "admin edita fotos" on storage.objects for update using (bucket_id = 'products' and auth.role() = 'authenticated');

drop policy if exists "admin borra fotos" on storage.objects;
create policy "admin borra fotos" on storage.objects for delete using (bucket_id = 'products' and auth.role() = 'authenticated');

-- ============================================================
--  FUNCIÓN: crear pedido y descontar stock atómicamente
-- ============================================================
create or replace function public.create_order_with_stock(
  customer_name text,
  customer_dni text,
  customer_phone text,
  customer_address text,
  items jsonb,
  total_amount numeric,
  coupon_code text default null,
  coupon_discount numeric default 0,
  status text default 'Pendiente'
)
returns jsonb
language plpgsql
security definer
as $$
declare
  item jsonb;
  pid bigint;
  qty int;
  available int;
  new_order orders%rowtype;
begin
  -- Verify and deduct stock for each item
  for item in select * from jsonb_array_elements(items)
  loop
    pid := (item->>'product_id')::bigint;
    qty := (item->>'qty')::int;

    select stock into available from products where id = pid for update;

    if available is null then
      raise exception 'Producto con id % no encontrado', pid;
    end if;

    if available < qty then
      raise exception 'Stock insuficiente para "%". Disponible: %, solicitado: %',
        item->>'name', available, qty;
    end if;

    update products set stock = stock - qty where id = pid;
  end loop;

  -- Create the order
  insert into orders (customer_name, customer_dni, customer_phone, customer_address,
                      items, total_amount, coupon_code, coupon_discount, status)
  values (customer_name, customer_dni, customer_phone, customer_address,
          items, total_amount, coupon_code, coupon_discount, status)
  returning * into new_order;

  return to_jsonb(new_order);
end;
$$;

-- ============================================================
--  FUNCIÓN: incrementar uso del cupón atómicamente
-- ============================================================
create or replace function public.increment_coupon_use(coupon_id bigint)
returns jsonb
language plpgsql
security definer
as $$
declare
  coupon coupons%rowtype;
begin
  select * into coupon from coupons where id = coupon_id for update;

  if coupon is null then
    raise exception 'Cupón no encontrado';
  end if;

  if coupon.max_uses is not null and coupon.uses_count >= coupon.max_uses then
    raise exception 'Cupón agotado';
  end if;

  update coupons
  set uses_count = uses_count + 1
  where id = coupon_id
  returning * into coupon;

  return to_jsonb(coupon);
end;
$$;

-- ============================================================
--  CATEGORÍAS INICIALES (accesorios para perros y gatos)
-- ============================================================
insert into categories (name, slug) values
  ('Collares, Correas y Arneses', 'collares-correas-arneses'),
  ('Juguetes',                    'juguetes'),
  ('Camas y Cuchas',              'camas-y-cuchas'),
  ('Comederos y Bebederos',       'comederos-y-bebederos'),
  ('Higiene y Cuidado',           'higiene-y-cuidado'),
  ('Ropa y Abrigos',              'ropa-y-abrigos'),
  ('Rascadores y Areneros',       'rascadores-y-areneros'),
  ('Transporte y Paseo',          'transporte-y-paseo')
on conflict (slug) do nothing;

-- ============================================================
--  PRODUCTO DE EJEMPLO: la cucha
--  (subí la foto después desde /admin → editar → subir foto)
-- ============================================================
insert into products (name, description, price, stock, is_featured, category_id)
select
  'Cucha Fibroplástica Modelo Grande',
  'Cucha de fibroplástico resistente, ideal para interior y exterior. Modelo grande, fácil de limpiar y muy duradera.',
  49999, 2, true,
  (select id from categories where slug = 'camas-y-cuchas')
where not exists (
  select 1 from products where name = 'Cucha Fibroplástica Modelo Grande'
);
